---
- name: Install windows feature
  hosts: all
  tasks:
    - name: installation of IIS role
      win_feature:
        name:
         - Web-Server
         - web-Common-Http
        include_sub_features: true
        include_management_tools: true
        state: present

 
    - name: Reboot if installing Web-Server feature requires it
      ansible.windows.win_reboot:
      when: win_feature.reboot_required
