---
- name: Create local group
  hosts: windows_servers
  tasks:
    - name: Add Bhagyesh user to group Test_Group_Admin
      ansible.windows.win_group:
        name: Test_Group_Admin
        members: Bhagyesh
        state: present
