---
- name: Run PowerShell code
  hosts: windows_servers
  gather_facts: no

  tasks:
    - name: Execute PowerShell code on ip-172-31-3-27.ap-south-1.compute.internal
      win_shell: |
        # Your PowerShell code here
        Import-PfxCertificate -FilePath \\172.31.2.169\Shares\Cert_setup\EclpEncryption.pfx -Password (ConvertTo-SecureString -String 'Allscripts#1' -AsPlainText -Force) -CertStoreLocation Cert:\LocalMachine\My
      when: inventory_hostname == "ip-172-31-3-27.ap-south-1.compute.internal"


    - name: Pause playbook execution for a specified duration
      pause:
        seconds: 60  # Adjust the wait time as needed
      when: inventory_hostname == "ip-172-31-3-27.ap-south-1.compute.internal"


    - name: Execute PowerShell code on ip-172-31-2-169.ap-south-1.compute.internal
      win_shell: |
        # Your PowerShell code here
        Import-PfxCertificate -FilePath \\172.31.2.169\Shares\Cert_setup\EclpEncryption.pfx -Password (ConvertTo-SecureString -String 'Allscripts#1' -AsPlainText -Force) -CertStoreLocation Cert:\LocalMachine\My
      when: inventory_hostname == "ip-172-31-2-169.ap-south-1.compute.internal"



