---
- name: update hosts file on windows server
  hosts: windows_servers
  tasks:
    - name: to add host entry
      win_lineinfile:
        path: C:\Windows\System32\drivers\etc\hosts
        line: "172.31.2.169  hosting"
        state: present
