---
- name: Run PowerShell code
  hosts: windows_servers
  gather_facts: no

  tasks:
    - name: Execute PowerShell code on Node 1
      win_shell: |
        # Your PowerShell code here
        # Example: Import PFX certificate


        Import-PfxCertificate -FilePath '\\172.31.2.169\Shares\Cert_setup\EclpEncryption.pfx' -Password (ConvertTo-SecureString -String 'Allscripts#1' -AsPlainText -Force) -CertStoreLocation Cert:\LocalMachine\My
      when: inventory_hostname == "ip-172-31-3-27.ap-south-1.compute.internal"



    - name: Pause playbook execution for 10 seconds after completing tasks on 172-31-3-27
      pause:
        seconds: 10
      when: inventory_hostname == "ip-172-31-3-27.ap-south-1.compute.internal"



    - name: Execute PowerShell code on other nodes
      win_shell: |
        # Your PowerShell code for other nodes here
        Import-PfxCertificate -FilePath '\\172.31.2.169\Shares\Cert_setup\EclpEncryption.pfx' -Password (ConvertTo-SecureString -String 'Allscripts#1' -AsPlainText -Force) -CertStoreLocation Cert:\LocalMachine\My

      when: inventory_hostname == "ip-172-31-2-169.ap-south-1.compute.internal"


